parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/a1ad/mikrotik-firewall-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: mikrotik-firewall-logs.log
log_type: mikrotik_drop
labels: {}
ignore_parsers: false
override_statics: []
